version: "3"
services:
  jupyter:
    build:
      context: ./docker
    image: {{ cookiecutter.project_slug }}
    volumes:
      - ./playground:/home/playground
      - ./data:/home/data
      - ./src:/home/src
      - ./models:/home/models
      - ./reports:/home/reports
      - ./references:/home/references
    ports:
      - {{ cookiecutter.jupyter_host_port }}:8888
    command: "jupyter lab"
